version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0
executors:
  nailapp-executor:
    docker:
      - image: cimg/ruby:3.3.0-browsers
        environment:
          RAILS_ENV: test
          NAILAPP_HOST: localhost
          NAILAPP_USER: postgres
      - image: cimg/postgres:15.4
        environment:
          POSTGRES_USER: nailapp
          POSTGRES_PASSWORD: nailapp
          POSTGRES_DB: nail_appointments_test
    working_directory: ~/nailapp  
commands:
  setup-bundler:
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v '2.5.14'
      # Restore bundle cache
      - restore_cache:
          keys:
          - nailapp-v1-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: nailapp-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
jobs:
  build:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker: 
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    executor: nailapp-executor
    parallelism: 3
    steps:
      - attach_workspace:
          at: '~/nailapp'
      - checkout
      - setup-bundler
      - run: ruby --version
      - run: sudo apt install postgresql-client
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:setup
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build