require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/availabilities", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Availability. As you add validations to Availability, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Availability.create! valid_attributes
      get availabilities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      availability = Availability.create! valid_attributes
      get availability_url(availability)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_availability_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      availability = Availability.create! valid_attributes
      get edit_availability_url(availability)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Availability" do
        expect {
          post availabilities_url, params: { availability: valid_attributes }
        }.to change(Availability, :count).by(1)
      end

      it "redirects to the created availability" do
        post availabilities_url, params: { availability: valid_attributes }
        expect(response).to redirect_to(availability_url(Availability.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Availability" do
        expect {
          post availabilities_url, params: { availability: invalid_attributes }
        }.to change(Availability, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post availabilities_url, params: { availability: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested availability" do
        availability = Availability.create! valid_attributes
        patch availability_url(availability), params: { availability: new_attributes }
        availability.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the availability" do
        availability = Availability.create! valid_attributes
        patch availability_url(availability), params: { availability: new_attributes }
        availability.reload
        expect(response).to redirect_to(availability_url(availability))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        availability = Availability.create! valid_attributes
        patch availability_url(availability), params: { availability: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested availability" do
      availability = Availability.create! valid_attributes
      expect {
        delete availability_url(availability)
      }.to change(Availability, :count).by(-1)
    end

    it "redirects to the availabilities list" do
      availability = Availability.create! valid_attributes
      delete availability_url(availability)
      expect(response).to redirect_to(availabilities_url)
    end
  end
end
